name = "CustomTkinter"
uuid = "89103bc4-4636-4963-a596-e5e62bd502f6"
authors = ["dzonimn"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
